/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        popover: 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        destructive: 'var(--destructive)',
        'destructive-foreground': 'var(--destructive-foreground)',
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        'warm-cream': 'var(--warm-cream)',
        'banana-yellow': 'var(--banana-yellow)',
        'deep-brown': 'var(--deep-brown)',
        'sage-green': 'var(--sage-green)',
        'light-sage': 'var(--light-sage)',
        'warm-beige': 'var(--warm-beige)',
        'soft-yellow': 'var(--soft-yellow)',
        'warm-sage': 'var(--warm-sage)',
      },
    },
  },
  plugins: [],
};
